name: Feature Check
on:
  pull_request:

jobs:
  linters:
    name: Run linters
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write
    strategy:
      fail-fast: false
      matrix:
        feature:
          - mail
          - logging
          - backend
          - db
          - auth
          - error
          - storage
          - backend,auth
          - backend,db,auth
          - backend,db,auth,frontend
          - endpoints
          - endpoints,storage
          - endpoints,metrics
          - endpoints,metrics,frontend
          - endpoints,frontend
          - endpoints,frontend,avatar
          - endpoints,frontend,avatar,storage
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: dtolnay/rust-toolchain@4cda84d5c5c54efe2404f9d843567869ab1699d4 # stable
        with:
          components: rustfmt,clippy

      - name: Sanitize cache key
        id: sanitize
        run: |
          CLEAN_FEATURE=$(echo "${{ matrix.feature }}" | tr ',' '-')
          echo "clean_feature=$CLEAN_FEATURE" >> $GITHUB_OUTPUT

      - name: Cache cargo and rust files
        id: rust_cache
        uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
        with:
          cache-on-failure: true
          shared-key: "linter_cache-${{ steps.sanitize.outputs.clean_feature }}"

      - name: Run Clippy
        run: cargo clippy --features "${{ matrix.feature }}" --no-default-features -- -D warnings
