name: Tests
on:
  pull_request:

jobs:
  build_and_test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3
        id: app-token
        with:
          client-id: ${{ secrets.COMMIT_BOT_CLIENT_ID }}
          private-key: ${{ secrets.COMMIT_BOT_PRIVATE_KEY }}
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
        with:
          components: rustfmt,clippy

      - name: Cache cargo and rust files
        id: rust_cache
        uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
        with:
          cache-on-failure: true
          shared-key: "test_cache"

      - uses: taiki-e/install-action@0c80bcf54d007ab0e714c95f3bcc43c387707535 # nextest
      - name: "Build and test"
        run: cargo nextest run --workspace --all-features

      - name: Upload Test Result File
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: test-results
          path: ${{ github.workspace }}/target/nextest/default/junit.xml
          retention-days: 5

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@d0a4676d0e0b938bc201470d88276b7c74c712b3 # v2
        if: always()
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          files: |
            ${{ github.workspace }}/target/nextest/default/junit.xml
